version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

issues:
  # Exclude specific files or directories from certain linters
  exclude-rules:
    # Exclude unused warnings for crypto/sphincsplus_256s (WIP)
    - path: crypto/sphincsplus_256s/
      linters:
        - unused
    # Exclude unused warnings for test helper functions
    - path: _test\.go
      linters:
        - unused
