package ml_dsa_87

const (
	CRYPTO_PUBLIC_KEY_BYTES = SEED_BYTES + K*POLY_T1_PACKED_BYTES
	CRYPTO_SECRET_KEY_BYTES = 2*SEED_BYTES + TR_BYTES + L*POLY_ETA_PACKED_BYTES + K*POLY_ETA_PACKED_BYTES + K*POLY_T0_PACKED_BYTES
	// CRYPTO_BYTES is the signature size in bytes
	CRYPTO_BYTES = C_TILDE_BYTES + L*POLY_Z_PACKED_BYTES + POLY_VEC_H_PACKED_BYTES

	SHAKE128_RATE         = 168
	SHAKE256_RATE         = 136
	STREAM128_BLOCK_BYTES = SHAKE128_RATE
	STREAM256_BLOCK_BYTES = SHAKE256_RATE

	POLY_UNIFORM_N_BLOCKS        = (768 + STREAM128_BLOCK_BYTES - 1) / STREAM128_BLOCK_BYTES
	POLY_UNIFORM_ETA_N_BLOCKS    = (136 + STREAM256_BLOCK_BYTES - 1) / STREAM256_BLOCK_BYTES
	POLY_UNIFORM_GAMMA1_N_BLOCKS = (POLY_Z_PACKED_BYTES + STREAM256_BLOCK_BYTES - 1) / STREAM256_BLOCK_BYTES

	SEED_BYTES = 32
	CRH_BYTES  = 64 // hash of public key
	TR_BYTES   = 64
	RND_BYTES  = 32
	N          = 256
	Q          = 8380417
	Q_INV      = 58728449 // -q^(-1) mod 2^32
	D          = 13

	K            = 8
	L            = 7
	ETA          = 2
	TAU          = 60
	BETA         = 120
	GAMMA1       = 1 << 19
	GAMMA2       = (Q - 1) / 32
	OMEGA        = 75
	C_TILDE_BYTES = 64

	// Polynomial sizes
	POLY_T1_PACKED_BYTES    = 320
	POLY_T0_PACKED_BYTES    = 416
	POLY_ETA_PACKED_BYTES   = 96
	POLY_Z_PACKED_BYTES     = 640
	POLY_VEC_H_PACKED_BYTES = OMEGA + K
	POLY_W1_PACKED_BYTES    = 128
)
